### ISSUE TITLE
Installing Old Cport on my local computer

### ISSUE THREAD

**Issue by ankush290307** [haddocking/cport#83]
Hi Is there a way I can install cport on my local system? as I am used to running cport instead to whiscky server.

**Comment by rvhonorato** [comment]
Hi @ankush290307, unfortunately that is not possible - we had to take it down because it was raising security issues in our server and most of the predictors it was using were no longer available 😞 

We are actively working on this new version and currently benchmarking the predictions! Meanwhile you could try to use [Arctic3D](https://bianca.science.uu.nl/arctic3d/) which does data retrieval instead of prediction.
